name: Fetch RSS & AI

on:
  schedule:
    # kör varje hel timme (UTC)
    - cron: '0 * * * *'
  workflow_dispatch:   # gör att du kan köra manuellt

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Call /admin/run-fetch
        run: |
          curl -X POST \
               -H "X-Admin-Token: ${{ secrets.ADMIN_TOKEN }}" \
               https://ai-nyheter-backend.onrender.com/admin/run-fetch
